# Letters come from the LETTERS font here:
# http://patorjk.com/software/taag/#p=display&f=Letters&t=U

letters = {
    'A': '  AAA   \n AAAAA  \nAA   AA \nAAAAAAA \nAA   AA \n        ',
    'B': 'BBBBB   \nBB   B  \nBBBBBB  \nBB   BB \nBBBBBB  \n        ',
    'C': ' CCCCC  \nCC    C \nCC      \nCC    C \n CCCCC  \n        ', 
    'D': 'DDDDD   \nDD  DD  \nDD   DD \nDD   DD \nDDDDDD  \n        ', 
    'E': 'EEEEEEE \nEE      \nEEEEE   \nEE      \nEEEEEEE \n        ',
    'F': 'FFFFFFF \nFF      \nFFFF    \nFF      \nFF      \n        ',
    'G': '  GGGG  \n GG  GG \nGG      \nGG   GG \n GGGGGG \n        ', 
    'H': 'HH   HH \nHH   HH \nHHHHHHH \nHH   HH \nHH   HH \n        ', 
    'I': 'IIIII \n III  \n III  \n III  \nIIIII \n      ',
    'J': '    JJJ \n    JJJ \n    JJJ \nJJ  JJJ \n JJJJJ  \n        ', 
    'K': 'KK  KK \nKK KK  \nKKKK   \nKK KK  \nKK  KK \n       ',
    'L': 'LL      \nLL      \nLL      \nLL      \nLLLLLLL \n        ', 
    'M': 'MM    MM \nMMM  MMM \nMM MM MM \nMM    MM \nMM    MM \n         ',
    'N': 'NN   NN \nNNN  NN \nNN N NN \nNN  NNN \nNN   NN \n        ,
    'O': ' OOOOO  \nOO   OO \nOO   OO \nOO   OO \n OOOO0  \n        ',
    'P': 'PPPPPP  \nPP   PP \nPPPPPP  \nPP      \nPP      \n        ',
    'Q': ' QQQQQ  \nQQ   QQ \nQQ   QQ \nQQ  QQ  \n QQQQ Q \n        ',
    'R': 'RRRRRR  \nRR   RR \nRRRRRR  \nRR  RR  \nRR   RR \n        ',
    'S': ' SSSSS  \nSS      \n SSSSS  \n     SS \n SSSSS  \n        ',
    'T': 'TTTTTTT \n  TTT   \n  TTT   \n  TTT   \n  TTT   \n        ',
    'U': 'UU   UU \nUU   UU \nUU   UU \nUU   UU \n UUUUU  \n        ',
    'V': 'VV     VV \nVV     VV \n VV   VV  \n  VV VV   \n   VVV    \n          ',
    'W': 'WW     WW \nWW     WW \nWW  W  WW \n  W WWW W  \n  W   W   \n           ',
    'X': 'XX    XX \n XX  XX  \n  XXXX   \n XX  XX  \nXX    XX \n         ',
    'Y': 'YY   YY \nYY   YY \n YYYYY  \n  YYY   \n  YYY   \n        ',
    'Z': 'ZZZZZ \n   ZZ \n  ZZ  \n ZZ   \nZZZZZ \n      ',
    'a': '',
    'b': '',
    'c': '',
    'd': '',
    'e': '',
    'f': '',
    'g': '',
    'h': '',
    'i': '',
    'j': '',
    'k': '',
    'l': '',
    'm': '',
    'n': '',
    'o': '',
    'p': '',
    'q': '',
    'r': '',
    's': '',
    't': '',
    'u': '',
    'v': '',
    'w': '',
    'x': '',
    'y': '',
    'z': '',
    ' ': '',
    ',': '',
    '.': '',
    '!': '',
    '?': '',
    '"': '',
    "'": '',
    '-': '',
    '_': '',
    '=': '',
    '<': '',
    '>': '',
    '@': '',
    '#': '',
    '$': '',
    '%': '',
    '^': '',
    '&': '',
    '*': '',
    '(': '',
    ')': '',
}