# Letters come from the LETTERS font here:
# http://patorjk.com/software/taag/#p=display&f=Letters&t=U

letters = {
    'A': '  AAA   \n AAAAA  \nAA   AA \nAAAAAAA \nAA   AA \n        '.split('\n'),
    'B': 'BBBBB   \nBB   B  \nBBBBBB  \nBB   BB \nBBBBBB  \n        '.split('\n'),
    'C': ' CCCCC  \nCC    C \nCC      \nCC    C \n CCCCC  \n        '.split('\n'), 
    'D': 'DDDDD   \nDD  DD  \nDD   DD \nDD   DD \nDDDDDD  \n        '.split('\n'), 
    'E': 'EEEEEEE \nEE      \nEEEEE   \nEE      \nEEEEEEE \n        '.split('\n'),
    'F': 'FFFFFFF \nFF      \nFFFF    \nFF      \nFF      \n        '.split('\n'),
    'G': '  GGGG  \n GG  GG \nGG      \nGG   GG \n GGGGGG \n        '.split('\n'), 
    'H': 'HH   HH \nHH   HH \nHHHHHHH \nHH   HH \nHH   HH \n        '.split('\n'), 
    'I': 'IIIII \n III  \n III  \n III  \nIIIII \n      '.split('\n'),
    'J': '    JJJ \n    JJJ \n    JJJ \nJJ  JJJ \n JJJJJ  \n        '.split('\n'), 
    'K': 'KK  KK \nKK KK  \nKKKK   \nKK KK  \nKK  KK \n       '.split('\n'),
    'L': 'LL      \nLL      \nLL      \nLL      \nLLLLLLL \n        '.split('\n'), 
    'M': 'MM    MM \nMMM  MMM \nMM MM MM \nMM    MM \nMM    MM \n         '.split('\n'),
    'N': 'NN   NN \nNNN  NN \nNN N NN \nNN  NNN \nNN   NN \n        '.split('\n'),
    'O': ' OOOOO  \nOO   OO \nOO   OO \nOO   OO \n OOOO0  \n        '.split('\n'),
    'P': 'PPPPPP  \nPP   PP \nPPPPPP  \nPP      \nPP      \n        '.split('\n'),
    'Q': ' QQQQQ  \nQQ   QQ \nQQ   QQ \nQQ  QQ  \n QQQQ Q \n        '.split('\n'),
    'R': 'RRRRRR  \nRR   RR \nRRRRRR  \nRR  RR  \nRR   RR \n        '.split('\n'),
    'S': ' SSSSS  \nSS      \n SSSSS  \n     SS \n SSSSS  \n        '.split('\n'),
    'T': 'TTTTTTT \n  TTT   \n  TTT   \n  TTT   \n  TTT   \n        '.split('\n'),
    'U': 'UU   UU \nUU   UU \nUU   UU \nUU   UU \n UUUUU  \n        '.split('\n'),
    'V': 'VV     VV \nVV     VV \n VV   VV  \n  VV VV   \n   VVV    \n          '.split('\n'),
    'W': 'WW     WW \nWW     WW \nWW  W  WW \n  W WWW W  \n  W   W   \n           '.split('\n'),
    'X': 'XX    XX \n XX  XX  \n  XXXX   \n XX  XX  \nXX    XX \n         '.split('\n'),
    'Y': 'YY   YY \nYY   YY \n YYYYY  \n  YYY   \n  YYY   \n        '.split('\n'),
    'Z': 'ZZZZZ \n   ZZ \n  ZZ  \n ZZ   \nZZZZZ \n      '.split('\n'),
    'a': '        \n  aa aa \n aa aaa \naa  aaa \n aaa aa \n        '.split('\n'),
    'b': 'bb      \nbb      \nbbbbbb  \nbb   bb \nbbbbbb  \n        '.split('\n'),
    'c': '       \n  cccc \ncc     \ncc     \n ccccc \n       '.split('\n'),
    'd': '     dd \n     dd \n dddddd \ndd   dd \n dddddd \n        '.split('\n'),
    'e': '       \n  eee  \nee   e \neeeee  \n eeeee \n       '.split('\n'),
    'f': ' fff \nff   \nffff \nff   \nff   \n     '.split('\n'),
    'g': '        \n gggggg \ngg   gg \nggggggg \n     gg \n ggggg  '.split('\n'),
    'h': 'hh      \nhh      \nhhhhhh  \nhh   hh \nhh   hh \n        '.split('\n'),
    'i': 'iii \n    \niii \niii \niii \n    '.split('\n'),
    'j': '  jjj \n      \n  jjj \n  jjj \n  jjj \njjjj  '.split('\n'),
    'k': 'kk     \nkk  kk \nkkkkk  \nkk kk  \nkk  kk \n       '.split('\n'),
    'l': 'lll \nlll \nlll \nlll \nlll     '.split('\n'),
    'm': '            \nmm mm mmmm  \nmmm  mm  mm \nmmm  mm  mm \nmmm  mm  mm \n            '.split('\n'),
    'n': '        \nnn nnn  \nnnn  nn \nnn   nn \nnn   nn \n        '.split('\n'),
    'o': '       \n oooo  \noo  oo \noo  oo \n oooo  \n       '.split('\n'),
    'p': '        \npp pp   \nppp  pp \npppppp  \npp      \npp      '.split('\n'),
    'q': '        \n  qqqqq \nqq   qq \n qqqqqq \n     qq \n     qq '.split('\n'),
    'r': '       \nrr rr  \nrrr  r \nrr     \nrr     \n       '.split('\n'),
    's': '      \n sss  \ns     \n sss  \n    s \n sss  '.split('\n'),
    't': 'tt    \ntt    \ntttt  \ntt    \n tttt \n      '.split('\n'),
    'u': '        \nuu   uu \nuu   uu \nuu   uu \n uuuu u \n        '.split('\n'),
    'v': '        \nvv   vv \n vv vv  \n  vvv   \n   v    \n        '.split('\n'),
    'w': '           \nww      ww \nww      ww \n ww ww ww  \n  ww  ww   \n           '.split('\n'),
    'x': '       \nxx  xx \n  xx   \n  xx   \nxx  xx \n       '.split('\n'),
    'y': '        \nyy   yy \nyy   yy \n yyyyyy \n     yy \n yyyyy  '.split('\n'),
    'z': '      \nzzzzz \n  zz  \n zz   \nzzzzz \n      '.split('\n'),
    ' ': '    \n    \n    \n    \n    '.split('\n'),
    ',': '    \n    \n    \n ,  \n,,, \n,,  '.split('\n'),
    '.': '    \n    \n    \n... \n... \n    '.split('\n'),
    '!': '!!! \n!!! \n!!! \n    \n!!! \n    '.split('\n'),
    '?': ' ???  \n?? ?? \n   ?? \n  ??  \n  ??  \n      '.split('\n'),
    '"': '""""" \n""""" \n """  \n      \n      \n      '.split('\n'),
    "'": " '  \n''' \n''  \n    \n    \n    ".split('\n'),
    '-': '        \n        \n _____  \n        \n        \n        '.split('\n'),
    '_': '        \n        \n        \n        \n_______ \n        '.split('\n'),
    '=': '        \n        \n======= \n======= \n        \n        '.split('\n'),
    '<': '     \n <<< \n<<<  \n<<<  \n <<< \n     '.split('\n'),
    '>': '     \n>>>  \n >>> \n >>> \n>>>  \n     '.split('\n'),
    '@': '  @@@@  \n @ @@ @ \n@ @  @@ \n@  @@@  \n @@@@@  \n        '.split('\n'),
    '#': '         \n  ## ##  \n ####### \n ####### \n  ## ##  \n         '.split('\n'),
    '$': ' /|-\ \n/ |   \n\-|-\ \n  | | \n\-|-/ \n      '.split('\n'),
    '%': '%%  %% \n%% %%  \n  %%   \n %% %% \n%%  %% \n       '.split('\n'),
    '^': ' ^^  \n^^^^ \n^  ^ \n     \n     \n     '.split('\n'),
    '&': '  &&&    \n && &&   \n &&&&&&& \n&&& &&   \n &&&&&&& \n         '.split('\n'),
    '*': '      \n*   * \n ***  \n ***  \n*   * \n      '.split('\n'),
    '(': '     \n ((( \n(((  \n(((  \n(((  \n ((( '.split('\n'),
    ')': '     \n)))  \n ))) \n ))) \n ))) \n)))  '.split('\n'),
    '[': '[[[[ \n[[   \n[[   \n[[   \n[[[[ \n     '.split('\n'),
    ']': ']]]] \n  ]] \n  ]] \n  ]] \n]]]] \n     '.split('\n'),
    '{': '   {{ \n  {{  \n{{{   \n{{{   \n  {{  \n   {{ '.split('\n'),
    '}': '}}    \n }}   \n  }}} \n  }}} \n }}   \n}}    '.split('\n'),
    '`': ' `  \n``` \n `` \n    \n    \n    '.split('\n'),
    '~': '       \n ~~ ~~ \n~  ~   \n       \n       \n       '.split('\n'),
}